# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028429e1b088095477fb0413e60bd2cc2ed9cd1ea9cb8c6400f2808b8f230105af12cca8276296b10a9497dbc21249bd268830cefb4d3718d08ffe413e74fa28

test:
  secret_key_base: 7a6017df58a6191e3b558644a3854516cc90bc3be935f6ba380831c89dfef5e598ade580f38bc0b062ac58c6201256e7c0d4ef1fa0cdbd86c6b629cf3709d57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
